---
title: "Input"
author: "Alex Kan -lexokan"
date: "December 1, 2017"
output: html_document
---

```{r, message = FALSE}
# Load packages 
library(tidyverse)
```

```{r, message = F}

# Def function to rename dataframe columns and tidy data into a useful format 

renameElection <- function(df) {
df <- rename(df,precinctName = `JURISDICTION: PRECINCT NAME`,
                  municipalityName = `JURISDICTION: MUNICIPALITY NAME`,
                  lastName = `NAME: LAST`,
                  firstName = `NAME: FIRST`,
                  statusCode = `STATUS CODE`,
                  middleName = `NAME: MIDDLE`,
                  ethnictyCode = `ETHNICITY CODE`,
                  residentialStreet = `RESIDENTIAL ADDRESS: FULL STREET`, 
                  residentialCity = `RESIDENTIAL ADDRESS: CITY/STATE/ZIP`,
                  mailingStreet = `MAILING ADDRESS: LINE 1`,
                  mailingCity = `MAILING ADDRESS: CITY/STATE/ZIP`,
                  age = `AGE AT YEAR END`,
                  race = `RACE CODE`,
                  gender = `GENDER CODE`,
                  party = `PARTY CODE`,
                  electionYear = `ELECTION DATE`,
                  electionName = `ELECTION NAME`,
                  votedParty = `VOTED PARTY CODE`
    )

# Mutate to determine election year, create full name and full address features (for geocoding)

df <- df %>% 
    mutate(electionYear = substring(electionYear, 6,9),
           fullName = paste(firstName, middleName, lastName), 
           address = paste(mailingStreet, mailingCity))

# Substitute in blank space in a person lacks a middle name 
df$fullName <- gsub(" NA ", "  ", df$fullName)

# Substitute in # for apartment numbers 
df$residentialStreet <- gsub('# ', '',df$residentialStreet)

#df <- df[!duplicated(df[,"fullName"]),]

return(df)

}

```

```{r}
# Read in general and municipal election datasets and apply function

general <- read_csv("data/General.csv") %>%
    renameElection()

municipal <- read_csv("data/Municipal.csv") %>%
    renameElection()
```

```{r}
# Def function to determine the zipcode of each address 

scrapeZipcode <- function(x, n){
  substr(x, nchar(x)-n+1, nchar(x))
}
```

```{r}
# Def function to break up each dataset into 10,000 row segments in order to batch geoccode. 
# https://geocoding.geo.census.gov/geocoder/geographies/addressbatch?form used 

sliceGeocode <- function(df,type) { 
    
    iter <- 1
    for (i in seq(from = 1, to = nrow(df) - (nrow(df) %% 10000) + 1, by = 10000)) {
        
        # Create unique path for each of the segmented datasets 
        path <- paste("temp/", type, iter,".csv", sep = "")
        
        # Create a unique ID for each address, add its address and zipcode, and break into 10,000 row segements 
        section <- df %>%
            mutate(id = (1:nrow(df))) %>%
            select(id, mailingStreet, municipalityName) %>% 
            mutate(state = "NC", zip = scrapeZipcode(df$mailingCity, 5)) %>%
            slice(i:(i+9999))
      
        # Save the segment
        write_csv(section, path, col_names = F)
        iter <- iter + 1
    }
}

```

```{r}
## Create segments for the municipal and general datasets 
sliceGeocode(general, "gen")
sliceGeocode(municipal, "muni")

write_csv(general, "temp/general.csv")
write_csv(municipal, "temp/municipal.csv")
combined <- rbind(general, municipal)

```

```{r}
## TODO: Geocode municipal addresses 
# Read in geocoded address coordinates 

#latLngGen <- read_csv("data/latLngGen.csv", col_names = F)

#general <- general %>% 
#    mutate(lat = latLngGen$X1, lng = latLngGen$X2)

#write_csv(general, "temp/genFinal.csv")


#latLngMuni <- read_csv("data/latLngMuni.csv", col_names = F)

```

